DROP DATABASE IF EXISTS employeeTracker_db;
CREATE DATABASE employeeTracker_db;
USE employeeTracker_db;

CREATE TABLE department(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
department_name VARCHAR(50) NOT NULL
);


CREATE TABLE role(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(30) NOT NULL,
salary DECIMAL NOT NULL,
department_id INT UNSIGNED NOT NULL,
CONSTRAINT fk_department FOREIGN KEY (department_id)
REFERENCES department(id)
);


CREATE TABLE employee(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
role_id INT UNSIGNED NOT NULL,
CONSTRAINT fk_role FOREIGN KEY (role_id)
REFERENCES role(id),
manager_id INT UNSIGNED NOT NULL,
CONSTRAINT fk_manager FOREIGN KEY(manager_id)
REFERENCES employee(id)
);


